### ISSUE TITLE
Micro-B connector does not sit flush with board

### ISSUE THREAD

**Issue by catequalsgood** [alvarop/usb_c_cable_tester#12]
Because of the bent lower lip of the micro-B port colliding with the board (see below) the part does not sit flush and can break off (it did on one of my boards anyway). The reference PCB layout (https://jlcpcb.com/fa9c3917-bd5c-4804-b018-3fa44680ab2e) seems so suggest a clearance of 0.7 mm between the board edge and that bent part of the connector.

Thank you for providing these files! Certainly a very useful tool to have around.

![screenshot](https://github.com/alvarop/usb_c_cable_tester/assets/70518425/b022a3c7-687b-4c2c-a91e-f5e9d733b468)

**Comment by alvarop** [comment]
Hopefully addressed in https://github.com/alvarop/usb_c_cable_tester/releases/tag/v2.1

**Comment by alvarop** [comment]
Fixed in v2.1 and later
