### ISSUE TITLE
Unsure if JLCPCB got this right

### ISSUE THREAD

**Issue by voltagex** [alvarop/usb_c_cable_tester#2]
(this would be better suited for GitHub Discussions but they're not enabled here)

![image](https://user-images.githubusercontent.com/83080728/202969103-87029ef4-5d41-4add-922a-e677e3f5691a.png)

I've sent them your photos back - it looks like they've dropped most of the parts off the board!

**Comment by alvarop** [comment]
@voltagex This is correct. The left side is what they will use :D
It is confusing though

**Comment by voltagex** [comment]
![image](https://user-images.githubusercontent.com/83080728/203001864-c6eb034e-ec64-4eca-8488-3e2e5eb14eb2.png)

To me it seems like there's only 3 components they're going to use? Some connectors are missing?

I guess I can just continue with the order and see what arrives.

**Comment by voltagex** [comment]
OK, yeah, the 2D render seems correct.
![Produce_DanZhi SMT_Snapshot Top 5174063A_Y1 SMT02211201032021](https://user-images.githubusercontent.com/83080728/203002691-2b4f7c89-5e0e-4d8d-9cfc-c294dc954a1b.png)

**Comment by alvarop** [comment]
:D

**Comment by voltagex** [comment]
This arrived today. I can get it to light up by probing with a multimeter, but not with a coin cell inserted. I do not like the battery holder at all

**Comment by tedder** [comment]
I would *love* to just get this off Tindie.

**Comment by alvarop** [comment]
Yeah, the battery holder isn’t great, you have to make sure you go over the negative and under the positive. 
![AE8A5DA5-1604-4701-B26A-26EDD3020877](https://user-images.githubusercontent.com/744129/204451244-63954cb1-ff74-4e72-b6bc-33f2d59416dc.jpeg)

![image](https://user-images.githubusercontent.com/744129/204451319-9b61b695-5934-45d6-8749-3dd9644e9986.jpg)
