### ISSUE TITLE
3D Printed/laser cut case

### ISSUE THREAD

**Issue by coryalder** [alvarop/usb_c_cable_tester#7]
Hello!

My local hackspace recently did a group-buy of this project, and I got myself 2 of them. They works great and a will be very useful. To make sure they last me a while, I designed a 3d printed / laser cut case for it. It has a 3d printed body, and a laser cut plexy top panel so you can see the lights on the board. I just wanted to link it here in case anybody else is looking to enclose theirs.

https://github.com/coryalder/usb-c-tester-case

**Comment by alvarop** [comment]
So cool! Thanks for sharing!

Going to add a link in the readme later so other folks can make their own :D

**Comment by alvarop** [comment]
I've added a link in the readme. Thanks again!
