### ISSUE TITLE
USB 3.0 Type B instead USB-type A

### ISSUE THREAD

**Issue by smesgr9000** [alvarop/usb_c_cable_tester#9]
Another suggestion would be to replace the USB 2.0 type B with an USB 3.0 type B plug. Like:
https://www.lcsc.com/product-detail/USB-Connectors_XUNPU-USB-306BWD-ARW_C2895032.html

This is downward compatible with earlier USB 2.0 plugs so could be used for older downward cables and newer ones.

**Comment by alvarop** [comment]
Added in https://github.com/alvarop/usb_c_cable_tester/releases/tag/v2.1
